// Auto-generated by TanStack Router — will be overwritten by the router plugin
// For now, create a simple manual route tree

import { createRootRoute, createRoute } from '@tanstack/react-router';

const rootRoute = createRootRoute({
  component: () => <div className="p-8"><h1>Sprintio</h1><p>AI-Enhanced Collaborative Work Management Platform</p></div>,
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => (
    <div className="flex min-h-screen items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold">Sprintio</h1>
        <p className="mt-2 text-lg text-gray-600">Sprint fast. Ship together.</p>
        <p className="mt-4 text-sm text-gray-400">Welcome to the development server.</p>
      </div>
    </div>
  ),
});

const routeTree = rootRoute.addChildren([indexRoute]);

export { routeTree };
