/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as GuestVerifyEmailExpiredRouteImport } from './routes/_guest.verify-email-expired'
import { Route as GuestVerifyEmailRouteImport } from './routes/_guest.verify-email'
import { Route as GuestVerifiedRouteImport } from './routes/_guest.verified'
import { Route as GuestResetPasswordSuccessRouteImport } from './routes/_guest.reset-password-success'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest.reset-password'
import { Route as GuestRegisterRouteImport } from './routes/_guest.register'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest.forgot-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedWorkspaceWorkspaceIdRouteImport } from './routes/_authenticated.workspace.$workspaceId'
import { Route as AuthenticatedWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_authenticated.workspace.$workspaceId.settings'
import { Route as AuthenticatedWorkspaceWorkspaceIdMembersRouteImport } from './routes/_authenticated.workspace.$workspaceId.members'
import { Route as AuthenticatedWorkspaceWorkspaceIdSettingsRolesRouteImport } from './routes/_authenticated.workspace.$workspaceId.settings.roles'
import { Route as AuthenticatedWorkspaceWorkspaceIdSettingsMembersRouteImport } from './routes/_authenticated.workspace.$workspaceId.settings.members'
import { Route as AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRouteImport } from './routes/_authenticated.workspace.$workspaceId.settings.general'
import { Route as AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRouteImport } from './routes/_authenticated.workspace.$workspaceId.settings.branding'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestVerifyEmailExpiredRoute = GuestVerifyEmailExpiredRouteImport.update({
  id: '/verify-email-expired',
  path: '/verify-email-expired',
  getParentRoute: () => GuestRoute,
} as any)
const GuestVerifyEmailRoute = GuestVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => GuestRoute,
} as any)
const GuestVerifiedRoute = GuestVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => GuestRoute,
} as any)
const GuestResetPasswordSuccessRoute =
  GuestResetPasswordSuccessRouteImport.update({
    id: '/reset-password-success',
    path: '/reset-password-success',
    getParentRoute: () => GuestRoute,
  } as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceWorkspaceIdRoute =
  AuthenticatedWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdSettingsRoute =
  AuthenticatedWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdMembersRoute =
  AuthenticatedWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute =
  AuthenticatedWorkspaceWorkspaceIdSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdSettingsRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute =
  AuthenticatedWorkspaceWorkspaceIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdSettingsRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute =
  AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdSettingsRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute =
  AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/reset-password-success': typeof GuestResetPasswordSuccessRoute
  '/verified': typeof GuestVerifiedRoute
  '/verify-email': typeof GuestVerifyEmailRoute
  '/verify-email-expired': typeof GuestVerifyEmailExpiredRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/members': typeof AuthenticatedWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/settings': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRouteWithChildren
  '/workspace/$workspaceId/settings/branding': typeof AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute
  '/workspace/$workspaceId/settings/general': typeof AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute
  '/workspace/$workspaceId/settings/members': typeof AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute
  '/workspace/$workspaceId/settings/roles': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/reset-password-success': typeof GuestResetPasswordSuccessRoute
  '/verified': typeof GuestVerifiedRoute
  '/verify-email': typeof GuestVerifyEmailRoute
  '/verify-email-expired': typeof GuestVerifyEmailExpiredRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/members': typeof AuthenticatedWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/settings': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRouteWithChildren
  '/workspace/$workspaceId/settings/branding': typeof AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute
  '/workspace/$workspaceId/settings/general': typeof AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute
  '/workspace/$workspaceId/settings/members': typeof AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute
  '/workspace/$workspaceId/settings/roles': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/reset-password-success': typeof GuestResetPasswordSuccessRoute
  '/_guest/verified': typeof GuestVerifiedRoute
  '/_guest/verify-email': typeof GuestVerifyEmailRoute
  '/_guest/verify-email-expired': typeof GuestVerifyEmailExpiredRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteWithChildren
  '/_authenticated/workspace/$workspaceId/members': typeof AuthenticatedWorkspaceWorkspaceIdMembersRoute
  '/_authenticated/workspace/$workspaceId/settings': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRouteWithChildren
  '/_authenticated/workspace/$workspaceId/settings/branding': typeof AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute
  '/_authenticated/workspace/$workspaceId/settings/general': typeof AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute
  '/_authenticated/workspace/$workspaceId/settings/members': typeof AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute
  '/_authenticated/workspace/$workspaceId/settings/roles': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-password-success'
    | '/verified'
    | '/verify-email'
    | '/verify-email-expired'
    | '/auth/callback'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/settings/branding'
    | '/workspace/$workspaceId/settings/general'
    | '/workspace/$workspaceId/settings/members'
    | '/workspace/$workspaceId/settings/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-password-success'
    | '/verified'
    | '/verify-email'
    | '/verify-email-expired'
    | '/auth/callback'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/settings/branding'
    | '/workspace/$workspaceId/settings/general'
    | '/workspace/$workspaceId/settings/members'
    | '/workspace/$workspaceId/settings/roles'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/register'
    | '/_guest/reset-password'
    | '/_guest/reset-password-success'
    | '/_guest/verified'
    | '/_guest/verify-email'
    | '/_guest/verify-email-expired'
    | '/auth/callback'
    | '/_authenticated/workspace/$workspaceId'
    | '/_authenticated/workspace/$workspaceId/members'
    | '/_authenticated/workspace/$workspaceId/settings'
    | '/_authenticated/workspace/$workspaceId/settings/branding'
    | '/_authenticated/workspace/$workspaceId/settings/general'
    | '/_authenticated/workspace/$workspaceId/settings/members'
    | '/_authenticated/workspace/$workspaceId/settings/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/verify-email-expired': {
      id: '/_guest/verify-email-expired'
      path: '/verify-email-expired'
      fullPath: '/verify-email-expired'
      preLoaderRoute: typeof GuestVerifyEmailExpiredRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/verify-email': {
      id: '/_guest/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof GuestVerifyEmailRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/verified': {
      id: '/_guest/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof GuestVerifiedRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/reset-password-success': {
      id: '/_guest/reset-password-success'
      path: '/reset-password-success'
      fullPath: '/reset-password-success'
      preLoaderRoute: typeof GuestResetPasswordSuccessRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspaceId': {
      id: '/_authenticated/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspaceId/settings': {
      id: '/_authenticated/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdRoute
    }
    '/_authenticated/workspace/$workspaceId/members': {
      id: '/_authenticated/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/workspace/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdRoute
    }
    '/_authenticated/workspace/$workspaceId/settings/roles': {
      id: '/_authenticated/workspace/$workspaceId/settings/roles'
      path: '/roles'
      fullPath: '/workspace/$workspaceId/settings/roles'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
    }
    '/_authenticated/workspace/$workspaceId/settings/members': {
      id: '/_authenticated/workspace/$workspaceId/settings/members'
      path: '/members'
      fullPath: '/workspace/$workspaceId/settings/members'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
    }
    '/_authenticated/workspace/$workspaceId/settings/general': {
      id: '/_authenticated/workspace/$workspaceId/settings/general'
      path: '/general'
      fullPath: '/workspace/$workspaceId/settings/general'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
    }
    '/_authenticated/workspace/$workspaceId/settings/branding': {
      id: '/_authenticated/workspace/$workspaceId/settings/branding'
      path: '/branding'
      fullPath: '/workspace/$workspaceId/settings/branding'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
    }
  }
}

interface AuthenticatedWorkspaceWorkspaceIdSettingsRouteChildren {
  AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute
  AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute
  AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute
  AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute
}

const AuthenticatedWorkspaceWorkspaceIdSettingsRouteChildren: AuthenticatedWorkspaceWorkspaceIdSettingsRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute:
      AuthenticatedWorkspaceWorkspaceIdSettingsBrandingRoute,
    AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute:
      AuthenticatedWorkspaceWorkspaceIdSettingsGeneralRoute,
    AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute:
      AuthenticatedWorkspaceWorkspaceIdSettingsMembersRoute,
    AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute:
      AuthenticatedWorkspaceWorkspaceIdSettingsRolesRoute,
  }

const AuthenticatedWorkspaceWorkspaceIdSettingsRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceIdSettingsRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceIdSettingsRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspaceIdRouteChildren {
  AuthenticatedWorkspaceWorkspaceIdMembersRoute: typeof AuthenticatedWorkspaceWorkspaceIdMembersRoute
  AuthenticatedWorkspaceWorkspaceIdSettingsRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRouteWithChildren
}

const AuthenticatedWorkspaceWorkspaceIdRouteChildren: AuthenticatedWorkspaceWorkspaceIdRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceIdMembersRoute:
      AuthenticatedWorkspaceWorkspaceIdMembersRoute,
    AuthenticatedWorkspaceWorkspaceIdSettingsRoute:
      AuthenticatedWorkspaceWorkspaceIdSettingsRouteWithChildren,
  }

const AuthenticatedWorkspaceWorkspaceIdRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceIdRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkspaceWorkspaceIdRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkspaceWorkspaceIdRoute:
    AuthenticatedWorkspaceWorkspaceIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestResetPasswordSuccessRoute: typeof GuestResetPasswordSuccessRoute
  GuestVerifiedRoute: typeof GuestVerifiedRoute
  GuestVerifyEmailRoute: typeof GuestVerifyEmailRoute
  GuestVerifyEmailExpiredRoute: typeof GuestVerifyEmailExpiredRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestResetPasswordSuccessRoute: GuestResetPasswordSuccessRoute,
  GuestVerifiedRoute: GuestVerifiedRoute,
  GuestVerifyEmailRoute: GuestVerifyEmailRoute,
  GuestVerifyEmailExpiredRoute: GuestVerifyEmailExpiredRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
