/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestVerifyEmailExpiredRouteImport } from './routes/_guest.verify-email-expired'
import { Route as GuestVerifyEmailRouteImport } from './routes/_guest.verify-email'
import { Route as GuestVerifiedRouteImport } from './routes/_guest.verified'
import { Route as GuestRegisterRouteImport } from './routes/_guest.register'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestVerifyEmailExpiredRoute = GuestVerifyEmailExpiredRouteImport.update({
  id: '/verify-email-expired',
  path: '/verify-email-expired',
  getParentRoute: () => GuestRoute,
} as any)
const GuestVerifyEmailRoute = GuestVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => GuestRoute,
} as any)
const GuestVerifiedRoute = GuestVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/verified': typeof GuestVerifiedRoute
  '/verify-email': typeof GuestVerifyEmailRoute
  '/verify-email-expired': typeof GuestVerifyEmailExpiredRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/verified': typeof GuestVerifiedRoute
  '/verify-email': typeof GuestVerifyEmailRoute
  '/verify-email-expired': typeof GuestVerifyEmailExpiredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/verified': typeof GuestVerifiedRoute
  '/_guest/verify-email': typeof GuestVerifyEmailRoute
  '/_guest/verify-email-expired': typeof GuestVerifyEmailExpiredRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verified'
    | '/verify-email'
    | '/verify-email-expired'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verified'
    | '/verify-email'
    | '/verify-email-expired'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/dashboard'
    | '/_guest/login'
    | '/_guest/register'
    | '/_guest/verified'
    | '/_guest/verify-email'
    | '/_guest/verify-email-expired'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/verify-email-expired': {
      id: '/_guest/verify-email-expired'
      path: '/verify-email-expired'
      fullPath: '/verify-email-expired'
      preLoaderRoute: typeof GuestVerifyEmailExpiredRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/verify-email': {
      id: '/_guest/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof GuestVerifyEmailRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/verified': {
      id: '/_guest/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof GuestVerifiedRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestVerifiedRoute: typeof GuestVerifiedRoute
  GuestVerifyEmailRoute: typeof GuestVerifyEmailRoute
  GuestVerifyEmailExpiredRoute: typeof GuestVerifyEmailExpiredRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestVerifiedRoute: GuestVerifiedRoute,
  GuestVerifyEmailRoute: GuestVerifyEmailRoute,
  GuestVerifyEmailExpiredRoute: GuestVerifyEmailExpiredRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
