services:
  api:
    restart: always
    environment:
      - NODE_ENV=production
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ai:
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    restart: always
