import type {
  TaskWithAssignee,
  SprintWithProgress,
  BoardHealthData,
  ActivityItem,
  MemberWorkload,
  WorkspaceData,
  BurndownPoint,
  VelocityPoint,
} from '@/types/dashboard';
import type { User } from '@sprintio/shared';

// ─── Users ───────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'u1',
    email: 'alex@sprintio.dev',
    name: 'Alex Chen',
    avatarUrl: null,
    emailVerified: true,
    role: 'owner',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
  {
    id: 'u2',
    email: 'sam@sprintio.dev',
    name: 'Sam Wilson',
    avatarUrl: null,
    emailVerified: true,
    role: 'admin',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
  {
    id: 'u3',
    email: 'jordan@sprintio.dev',
    name: 'Jordan Lee',
    avatarUrl: null,
    emailVerified: true,
    role: 'member',
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
  {
    id: 'u4',
    email: 'casey@sprintio.dev',
    name: 'Casey Morgan',
    avatarUrl: null,
    emailVerified: true,
    role: 'member',
    createdAt: '2026-04-05T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
  {
    id: 'u5',
    email: 'taylor@sprintio.dev',
    name: 'Taylor Swift',
    avatarUrl: null,
    emailVerified: true,
    role: 'guest',
    createdAt: '2026-05-20T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
];

// ─── Tasks ───────────────────────────────────────────────────────────────────

export const mockTasks: TaskWithAssignee[] = [
  {
    id: 't1',
    title: 'Fix authentication bug',
    description: null,
    status: 'todo',
    priority: 'urgent',
    assigneeId: 'u1',
    boardId: 'b1',
    columnId: 'c1',
    sprintId: 's1',
    position: 0,
    labels: ['bug', 'auth'],
    dueDate: '2026-07-19T00:00:00Z',
    createdAt: '2026-07-15T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[0],
  },
  {
    id: 't2',
    title: 'Add dark mode support',
    description: null,
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'u1',
    boardId: 'b1',
    columnId: 'c2',
    sprintId: 's1',
    position: 1,
    labels: ['feature', 'ui'],
    dueDate: '2026-07-25T00:00:00Z',
    createdAt: '2026-07-14T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[0],
  },
  {
    id: 't3',
    title: 'Write unit tests for auth module',
    description: null,
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u1',
    boardId: 'b1',
    columnId: 'c1',
    sprintId: 's1',
    position: 2,
    labels: ['testing'],
    dueDate: '2026-07-21T00:00:00Z',
    createdAt: '2026-07-13T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[0],
  },
  {
    id: 't4',
    title: 'Update API documentation',
    description: null,
    status: 'todo',
    priority: 'low',
    assigneeId: 'u1',
    boardId: 'b1',
    columnId: 'c1',
    sprintId: 's1',
    position: 3,
    labels: ['docs'],
    dueDate: '2026-07-23T00:00:00Z',
    createdAt: '2026-07-12T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[0],
  },
  {
    id: 't5',
    title: 'Refactor API middleware',
    description: null,
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'u2',
    boardId: 'b1',
    columnId: 'c2',
    sprintId: 's1',
    position: 4,
    labels: ['refactor', 'api'],
    dueDate: '2026-07-22T00:00:00Z',
    createdAt: '2026-07-11T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[1],
  },
  {
    id: 't6',
    title: 'Design onboarding flow',
    description: null,
    status: 'in_review',
    priority: 'medium',
    assigneeId: 'u3',
    boardId: 'b1',
    columnId: 'c3',
    sprintId: 's1',
    position: 5,
    labels: ['design', 'ux'],
    dueDate: '2026-07-20T00:00:00Z',
    createdAt: '2026-07-10T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[2],
  },
  {
    id: 't7',
    title: 'Fix responsive layout issues',
    description: null,
    status: 'done',
    priority: 'medium',
    assigneeId: 'u4',
    boardId: 'b1',
    columnId: 'c4',
    sprintId: 's1',
    position: 6,
    labels: ['bug', 'ui'],
    dueDate: '2026-07-18T00:00:00Z',
    createdAt: '2026-07-09T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[3],
  },
  {
    id: 't8',
    title: 'Set up CI/CD pipeline',
    description: null,
    status: 'done',
    priority: 'high',
    assigneeId: 'u2',
    boardId: 'b1',
    columnId: 'c4',
    sprintId: 's1',
    position: 7,
    labels: ['devops'],
    dueDate: '2026-07-17T00:00:00Z',
    createdAt: '2026-07-08T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[1],
  },
  {
    id: 't9',
    title: 'Implement search functionality',
    description: null,
    status: 'todo',
    priority: 'high',
    assigneeId: 'u1',
    boardId: 'b2',
    columnId: 'c5',
    sprintId: 's1',
    position: 0,
    labels: ['feature'],
    dueDate: '2026-07-24T00:00:00Z',
    createdAt: '2026-07-07T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[0],
  },
  {
    id: 't10',
    title: 'Add export to CSV',
    description: null,
    status: 'todo',
    priority: 'low',
    assigneeId: 'u3',
    boardId: 'b2',
    columnId: 'c5',
    sprintId: null,
    position: 1,
    labels: ['feature'],
    dueDate: null,
    createdAt: '2026-07-06T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[2],
  },
  {
    id: 't11',
    title: 'Performance audit',
    description: null,
    status: 'in_progress',
    priority: 'urgent',
    assigneeId: 'u2',
    boardId: 'b2',
    columnId: 'c6',
    sprintId: 's1',
    position: 2,
    labels: ['performance'],
    dueDate: '2026-07-19T00:00:00Z',
    createdAt: '2026-07-05T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    assignee: mockUsers[1],
  },
  {
    id: 't12',
    title: 'Update dependencies',
    description: null,
    status: 'todo',
    priority: 'none',
    assigneeId: null,
    boardId: 'b2',
    columnId: 'c5',
    sprintId: null,
    position: 3,
    labels: ['maintenance'],
    dueDate: null,
    createdAt: '2026-07-04T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
  },
];

// ─── Sprint ──────────────────────────────────────────────────────────────────

export const mockActiveSprint: SprintWithProgress = {
  id: 's1',
  projectId: 'p1',
  name: 'Sprint 3',
  goal: 'Ship authentication system',
  startDate: '2026-07-14T00:00:00Z',
  endDate: '2026-07-25T00:00:00Z',
  sprintStatus: 'active',
  createdAt: '2026-07-14T00:00:00Z',
  progress: 65,
  daysRemaining: 4,
  health: 'on_track',
  completedToday: 2,
  inProgress: 5,
  blocked: 1,
};

// ─── Boards ──────────────────────────────────────────────────────────────────

export const mockBoards: BoardHealthData[] = [
  {
    boardId: 'b1',
    name: 'Sprint Board',
    totalCards: 12,
    columns: [
      { name: 'To Do', count: 3, colorToken: 'muted-foreground' },
      { name: 'In Progress', count: 5, colorToken: 'primary' },
      { name: 'Review', count: 2, colorToken: '--priority-medium' },
      { name: 'Done', count: 2, colorToken: '--sprint-on-track' },
    ],
  },
  {
    boardId: 'b2',
    name: 'Bug Tracker',
    totalCards: 8,
    columns: [
      { name: 'Open', count: 4, colorToken: 'muted-foreground' },
      { name: 'In Progress', count: 2, colorToken: 'primary' },
      { name: 'Resolved', count: 2, colorToken: '--sprint-on-track' },
    ],
  },
  {
    boardId: 'b3',
    name: 'Feature Backlog',
    totalCards: 21,
    columns: [
      { name: 'Backlog', count: 12, colorToken: 'muted-foreground' },
      { name: 'Ready', count: 5, colorToken: 'primary' },
      { name: 'In Progress', count: 3, colorToken: '--priority-medium' },
      { name: 'Done', count: 1, colorToken: '--sprint-on-track' },
    ],
  },
];

// ─── Activity ────────────────────────────────────────────────────────────────

export const mockActivity: ActivityItem[] = [
  {
    id: 'a1',
    actor: { name: 'Alex Chen' },
    action: 'completed',
    target: '"Fix auth bug"',
    timestamp: '2 min ago',
  },
  {
    id: 'a2',
    actor: { name: 'Sam Wilson' },
    action: 'started',
    target: '"API refactor"',
    timestamp: '15 min ago',
  },
  {
    id: 'a3',
    actor: { name: 'Jordan Lee' },
    action: 'created',
    target: 'board "Q3 Planning"',
    timestamp: '1 hour ago',
  },
  {
    id: 'a4',
    actor: { name: 'Alex Chen' },
    action: 'commented',
    target: 'on "Add dark mode"',
    timestamp: '2 hours ago',
  },
  {
    id: 'a5',
    actor: { name: 'Sam Wilson' },
    action: 'updated',
    target: '"Sprint 3" goal',
    timestamp: '3 hours ago',
  },
  {
    id: 'a6',
    actor: { name: 'Casey Morgan' },
    action: 'completed',
    target: '"Fix responsive layout"',
    timestamp: '4 hours ago',
  },
  {
    id: 'a7',
    actor: { name: 'Jordan Lee' },
    action: 'started',
    target: '"Design onboarding"',
    timestamp: '5 hours ago',
  },
  {
    id: 'a8',
    actor: { name: 'Alex Chen' },
    action: 'created',
    target: 'task "Performance audit"',
    timestamp: '6 hours ago',
  },
];

// ─── Team Workload ───────────────────────────────────────────────────────────

export const mockTeamWorkload: MemberWorkload[] = [
  { id: 'u1', name: 'Alex Chen', assigned: 8, capacity: 10 },
  { id: 'u2', name: 'Sam Wilson', assigned: 6, capacity: 10 },
  { id: 'u3', name: 'Jordan Lee', assigned: 10, capacity: 10 },
  { id: 'u4', name: 'Casey Morgan', assigned: 3, capacity: 10 },
  { id: 'u5', name: 'Taylor Swift', assigned: 7, capacity: 10 },
];

// ─── Workspace ───────────────────────────────────────────────────────────────

export const mockWorkspace: WorkspaceData = {
  id: 'w1',
  name: 'Sprintio',
  slug: 'sprintio',
  description: 'Sprint management platform',
  logo: null,
  brandColor: '#4F46E5',
  customDomain: null,
  archivedAt: null,
  organizationId: null,
  plan: 'pro',
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-07-18T00:00:00Z',
  memberCount: 8,
  boardCount: 5,
  usage: [
    { label: 'Team members', current: 8, limit: 10, unit: 'members' },
    { label: 'Projects', current: 5, limit: 10, unit: 'projects' },
    { label: 'Storage', current: 2.4, limit: 5, unit: 'GB' },
    { label: 'API calls', current: 8500, limit: 10000, unit: 'calls' },
  ],
};

// ─── Analytics ───────────────────────────────────────────────────────────────

export const mockBurndownData: BurndownPoint[] = [
  { day: 'Day 1', ideal: 20, actual: 20 },
  { day: 'Day 2', ideal: 17.5, actual: 18 },
  { day: 'Day 3', ideal: 15, actual: 16 },
  { day: 'Day 4', ideal: 12.5, actual: 13 },
  { day: 'Day 5', ideal: 10, actual: 11 },
  { day: 'Day 6', ideal: 7.5, actual: 9 },
  { day: 'Day 7', ideal: 5, actual: 6 },
  { day: 'Day 8', ideal: 2.5, actual: 4 },
  { day: 'Day 9', ideal: 0, actual: null },
  { day: 'Day 10', ideal: 0, actual: null },
];

export const mockVelocityData: VelocityPoint[] = [
  { sprint: 'S1', planned: 18, completed: 15 },
  { sprint: 'S2', planned: 20, completed: 18 },
  { sprint: 'S3', planned: 22, completed: 14 },
  { sprint: 'S4', planned: 19, completed: 19 },
  { sprint: 'S5', planned: 21, completed: 17 },
];
